namespace HospitalManagmentSys.Presentation.Settings
{
    public partial class SettingsView
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        private void InitializeComponent()
        {
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges3 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges4 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges1 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges2 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges13 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges14 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges5 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges6 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges9 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges10 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges11 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges12 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges30 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges31 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges15 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges16 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges17 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges28 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges29 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges18 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges19 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges20 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges21 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges32 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges33 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges34 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges35 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges22 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges23 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges24 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges25 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges26 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges27 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            tlpRoot = new TableLayoutPanel();
            cardHeader = new Guna.UI2.WinForms.Guna2Panel();
            tlpHeader = new TableLayoutPanel();
            pHeaderText = new Panel();
            lblTitle = new Label();
            lblSubtitle = new Label();
            btnSave = new Guna.UI2.WinForms.Guna2Button();
            cardTabs = new Guna.UI2.WinForms.Guna2Panel();
            tlpTabs = new TableLayoutPanel();
            btnTabProfile = new Guna.UI2.WinForms.Guna2Button();
            btnTabQueue = new Guna.UI2.WinForms.Guna2Button();
            btnTabSystem = new Guna.UI2.WinForms.Guna2Button();
            cardProfile = new Guna.UI2.WinForms.Guna2Panel();
            tlpProfile = new TableLayoutPanel();
            pAvatarInfo = new Panel();
            btnAvatar = new Guna.UI2.WinForms.Guna2CircleButton();
            pUserInfo = new Panel();
            lblUserName = new Label();
            lblUserEmail = new Label();
            lblUserRole = new Guna.UI2.WinForms.Guna2Button();
            pProfileSection = new Guna.UI2.WinForms.Guna2Panel();
            tlpProfileFields = new TableLayoutPanel();
            lblProfileInfo = new Label();
            lblFullName = new Label();
            txtFullName = new Guna.UI2.WinForms.Guna2TextBox();
            lblEmail = new Label();
            txtEmail = new Guna.UI2.WinForms.Guna2TextBox();
            lblSpeciality = new Label();
            txtSpeciality = new Guna.UI2.WinForms.Guna2TextBox();
            lblPhone = new Label();
            txtPhone = new Guna.UI2.WinForms.Guna2TextBox();
            lblRolePermissions = new Label();
            pPermissions = new Panel();
            cardPermPatients = new Guna.UI2.WinForms.Guna2Panel();
            lblPermPatientsTitle = new Label();
            lblPermPatientsValue = new Label();
            cardPermAppointments = new Guna.UI2.WinForms.Guna2Panel();
            lblPermAppointmentsTitle = new Label();
            lblPermAppointmentsValue = new Label();
            cardPermReports = new Guna.UI2.WinForms.Guna2Panel();
            lblPermReportsTitle = new Label();
            lblPermReportsValue = new Label();
            lblProfileSub = new Label();
            tlpRoot.SuspendLayout();
            cardHeader.SuspendLayout();
            tlpHeader.SuspendLayout();
            pHeaderText.SuspendLayout();
            cardTabs.SuspendLayout();
            tlpTabs.SuspendLayout();
            cardProfile.SuspendLayout();
            tlpProfile.SuspendLayout();
            pAvatarInfo.SuspendLayout();
            pUserInfo.SuspendLayout();
            pProfileSection.SuspendLayout();
            tlpProfileFields.SuspendLayout();
            pPermissions.SuspendLayout();
            cardPermPatients.SuspendLayout();
            cardPermAppointments.SuspendLayout();
            cardPermReports.SuspendLayout();
            SuspendLayout();
            // tlpRoot
            tlpRoot.ColumnCount = 1;
            tlpRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            tlpRoot.Controls.Add(cardHeader, 0, 0);
            tlpRoot.Controls.Add(cardTabs, 0, 1);
            tlpRoot.Controls.Add(cardProfile, 0, 2);
            tlpRoot.Dock = DockStyle.Fill;
            tlpRoot.Location = new Point(24, 24);
            tlpRoot.Name = "tlpRoot";
            tlpRoot.RowCount = 3;
            tlpRoot.RowStyles.Add(new RowStyle());
            tlpRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 60F));
            tlpRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tlpRoot.Size = new Size(1100, 760);
            tlpRoot.TabIndex = 0;
            // cardHeader
            cardHeader.BackColor = Color.Transparent;
            cardHeader.BorderColor = Color.FromArgb(230, 234, 242);
            cardHeader.BorderRadius = 14;
            cardHeader.BorderThickness = 1;
            cardHeader.Controls.Add(tlpHeader);
            cardHeader.CustomizableEdges = customizableEdges3;
            cardHeader.Dock = DockStyle.Fill;
            cardHeader.FillColor = Color.White;
            cardHeader.Location = new Point(3, 3);
            cardHeader.Name = "cardHeader";
            cardHeader.Padding = new Padding(16);
            cardHeader.ShadowDecoration.BorderRadius = 14;
            cardHeader.ShadowDecoration.CustomizableEdges = customizableEdges4;
            cardHeader.ShadowDecoration.Enabled = true;
            cardHeader.Size = new Size(1094, 86);
            cardHeader.TabIndex = 0;
            // tlpHeader
            tlpHeader.ColumnCount = 2;
            tlpHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            tlpHeader.ColumnStyles.Add(new ColumnStyle());
            tlpHeader.Controls.Add(pHeaderText, 0, 0);
            tlpHeader.Controls.Add(btnSave, 1, 0);
            tlpHeader.Dock = DockStyle.Fill;
            tlpHeader.Location = new Point(16, 16);
            tlpHeader.Name = "tlpHeader";
            tlpHeader.RowCount = 1;
            tlpHeader.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tlpHeader.Size = new Size(1062, 54);
            tlpHeader.TabIndex = 0;
            // pHeaderText
            pHeaderText.Controls.Add(lblTitle);
            pHeaderText.Controls.Add(lblSubtitle);
            pHeaderText.Dock = DockStyle.Fill;
            pHeaderText.Location = new Point(3, 3);
            pHeaderText.Name = "pHeaderText";
            pHeaderText.Size = new Size(900, 48);
            pHeaderText.TabIndex = 0;
            // lblTitle
            lblTitle.AutoSize = true;
            lblTitle.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblTitle.ForeColor = Color.FromArgb(17, 24, 39);
            lblTitle.Location = new Point(0, 0);
            lblTitle.Name = "lblTitle";
            lblTitle.Size = new Size(106, 32);
            lblTitle.TabIndex = 0;
            lblTitle.Text = "Settings";
            // lblSubtitle
            lblSubtitle.AutoSize = true;
            lblSubtitle.Font = new Font("Segoe UI", 10F);
            lblSubtitle.ForeColor = Color.FromArgb(107, 114, 128);
            lblSubtitle.Location = new Point(0, 33);
            lblSubtitle.Name = "lblSubtitle";
            lblSubtitle.Size = new Size(324, 19);
            lblSubtitle.TabIndex = 1;
            lblSubtitle.Text = "Manage your preferences and system configuration";
            // btnSave
            btnSave.BorderRadius = 10;
            btnSave.CustomizableEdges = customizableEdges1;
            btnSave.FillColor = Color.FromArgb(26, 115, 232);
            btnSave.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnSave.ForeColor = Color.White;
            btnSave.Location = new Point(909, 8);
            btnSave.Margin = new Padding(3, 8, 3, 3);
            btnSave.Name = "btnSave";
            btnSave.ShadowDecoration.CustomizableEdges = customizableEdges2;
            btnSave.Size = new Size(150, 40);
            btnSave.TabIndex = 1;
            btnSave.Text = "💾  Save Changes";
            // cardTabs
            cardTabs.BackColor = Color.Transparent;
            cardTabs.BorderColor = Color.FromArgb(230, 234, 242);
            cardTabs.BorderRadius = 14;
            cardTabs.BorderThickness = 1;
            cardTabs.Controls.Add(tlpTabs);
            cardTabs.CustomizableEdges = customizableEdges13;
            cardTabs.Dock = DockStyle.Fill;
            cardTabs.FillColor = Color.White;
            cardTabs.Location = new Point(3, 95);
            cardTabs.Name = "cardTabs";
            cardTabs.Padding = new Padding(8);
            cardTabs.ShadowDecoration.CustomizableEdges = customizableEdges14;
            cardTabs.Size = new Size(1094, 54);
            cardTabs.TabIndex = 1;
            // tlpTabs - 3 columns بدل 4
            tlpTabs.ColumnCount = 3;
            tlpTabs.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33F));
            tlpTabs.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33F));
            tlpTabs.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 34F));
            tlpTabs.Controls.Add(btnTabProfile, 0, 0);
            tlpTabs.Controls.Add(btnTabQueue, 1, 0);
            tlpTabs.Controls.Add(btnTabSystem, 2, 0);
            tlpTabs.Dock = DockStyle.Fill;
            tlpTabs.Location = new Point(8, 8);
            tlpTabs.Name = "tlpTabs";
            tlpTabs.RowCount = 1;
            tlpTabs.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tlpTabs.Size = new Size(1078, 38);
            tlpTabs.TabIndex = 0;
            // btnTabProfile
            btnTabProfile.BorderRadius = 10;
            btnTabProfile.CustomizableEdges = customizableEdges5;
            btnTabProfile.Dock = DockStyle.Fill;
            btnTabProfile.FillColor = Color.FromArgb(240, 245, 255);
            btnTabProfile.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnTabProfile.ForeColor = Color.FromArgb(26, 115, 232);
            btnTabProfile.Location = new Point(3, 3);
            btnTabProfile.Name = "btnTabProfile";
            btnTabProfile.ShadowDecoration.CustomizableEdges = customizableEdges6;
            btnTabProfile.Size = new Size(349, 32);
            btnTabProfile.TabIndex = 0;
            btnTabProfile.Text = "Profile";
            // btnTabQueue
            btnTabQueue.BorderRadius = 10;
            btnTabQueue.CustomizableEdges = customizableEdges9;
            btnTabQueue.Dock = DockStyle.Fill;
            btnTabQueue.FillColor = Color.Transparent;
            btnTabQueue.Font = new Font("Segoe UI", 10F);
            btnTabQueue.ForeColor = Color.FromArgb(107, 114, 128);
            btnTabQueue.Location = new Point(358, 3);
            btnTabQueue.Name = "btnTabQueue";
            btnTabQueue.ShadowDecoration.CustomizableEdges = customizableEdges10;
            btnTabQueue.Size = new Size(349, 32);
            btnTabQueue.TabIndex = 1;
            btnTabQueue.Text = "Queue";
            // btnTabSystem
            btnTabSystem.BorderRadius = 10;
            btnTabSystem.CustomizableEdges = customizableEdges11;
            btnTabSystem.Dock = DockStyle.Fill;
            btnTabSystem.FillColor = Color.Transparent;
            btnTabSystem.Font = new Font("Segoe UI", 10F);
            btnTabSystem.ForeColor = Color.FromArgb(107, 114, 128);
            btnTabSystem.Location = new Point(713, 3);
            btnTabSystem.Name = "btnTabSystem";
            btnTabSystem.ShadowDecoration.CustomizableEdges = customizableEdges12;
            btnTabSystem.Size = new Size(362, 32);
            btnTabSystem.TabIndex = 2;
            btnTabSystem.Text = "System";
            // cardProfile
            cardProfile.BackColor = Color.Transparent;
            cardProfile.BorderColor = Color.FromArgb(230, 234, 242);
            cardProfile.BorderRadius = 14;
            cardProfile.BorderThickness = 1;
            cardProfile.Controls.Add(tlpProfile);
            cardProfile.CustomizableEdges = customizableEdges30;
            cardProfile.Dock = DockStyle.Fill;
            cardProfile.FillColor = Color.White;
            cardProfile.Location = new Point(3, 155);
            cardProfile.Name = "cardProfile";
            cardProfile.Padding = new Padding(24);
            cardProfile.ShadowDecoration.BorderRadius = 14;
            cardProfile.ShadowDecoration.CustomizableEdges = customizableEdges31;
            cardProfile.ShadowDecoration.Enabled = true;
            cardProfile.Size = new Size(1094, 602);
            cardProfile.TabIndex = 2;
            // tlpProfile
            tlpProfile.ColumnCount = 1;
            tlpProfile.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            tlpProfile.Controls.Add(pAvatarInfo, 0, 0);
            tlpProfile.Controls.Add(pProfileSection, 0, 1);
            tlpProfile.Dock = DockStyle.Fill;
            tlpProfile.Location = new Point(24, 24);
            tlpProfile.Name = "tlpProfile";
            tlpProfile.RowCount = 2;
            tlpProfile.RowStyles.Add(new RowStyle(SizeType.Absolute, 100F));
            tlpProfile.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tlpProfile.Size = new Size(1046, 554);
            tlpProfile.TabIndex = 0;
            // pAvatarInfo
            pAvatarInfo.Controls.Add(btnAvatar);
            pAvatarInfo.Controls.Add(pUserInfo);
            pAvatarInfo.Dock = DockStyle.Fill;
            pAvatarInfo.Location = new Point(3, 3);
            pAvatarInfo.Name = "pAvatarInfo";
            pAvatarInfo.Size = new Size(1040, 94);
            pAvatarInfo.TabIndex = 0;
            // btnAvatar
            btnAvatar.Enabled = false;
            btnAvatar.FillColor = Color.FromArgb(239, 246, 255);
            btnAvatar.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            btnAvatar.ForeColor = Color.FromArgb(37, 99, 235);
            btnAvatar.Location = new Point(0, 16);
            btnAvatar.Name = "btnAvatar";
            btnAvatar.ShadowDecoration.CustomizableEdges = customizableEdges15;
            btnAvatar.Size = new Size(64, 64);
            btnAvatar.TabIndex = 0;
            btnAvatar.Text = "DM";
            // pUserInfo
            pUserInfo.Controls.Add(lblUserName);
            pUserInfo.Controls.Add(lblUserEmail);
            pUserInfo.Controls.Add(lblUserRole);
            pUserInfo.Location = new Point(80, 5);
            pUserInfo.Name = "pUserInfo";
            pUserInfo.Size = new Size(428, 75);
            pUserInfo.TabIndex = 1;
            // lblUserName
            lblUserName.AutoSize = true;
            lblUserName.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblUserName.ForeColor = Color.FromArgb(17, 24, 39);
            lblUserName.Location = new Point(0, 0);
            lblUserName.Name = "lblUserName";
            lblUserName.Size = new Size(160, 25);
            lblUserName.TabIndex = 0;
            lblUserName.Text = "Dr. Michael Chen";
            // lblUserEmail
            lblUserEmail.AutoSize = true;
            lblUserEmail.Font = new Font("Segoe UI", 10F);
            lblUserEmail.ForeColor = Color.FromArgb(107, 114, 128);
            lblUserEmail.Location = new Point(0, 28);
            lblUserEmail.Name = "lblUserEmail";
            lblUserEmail.Size = new Size(140, 19);
            lblUserEmail.TabIndex = 1;
            lblUserEmail.Text = "mchen@hospital.com";
            // lblUserRole
            lblUserRole.BorderRadius = 8;
            lblUserRole.CustomizableEdges = customizableEdges16;
            lblUserRole.Enabled = false;
            lblUserRole.FillColor = Color.FromArgb(34, 197, 94);
            lblUserRole.Font = new Font("Segoe UI", 8F, FontStyle.Bold);
            lblUserRole.ForeColor = Color.White;
            lblUserRole.Location = new Point(0, 50);
            lblUserRole.Name = "lblUserRole";
            lblUserRole.ShadowDecoration.CustomizableEdges = customizableEdges17;
            lblUserRole.Size = new Size(70, 22);
            lblUserRole.TabIndex = 2;
            lblUserRole.Text = "Doctor";
            // pProfileSection
            pProfileSection.Controls.Add(tlpProfileFields);
            pProfileSection.CustomizableEdges = customizableEdges28;
            pProfileSection.Dock = DockStyle.Fill;
            pProfileSection.Location = new Point(3, 103);
            pProfileSection.Name = "pProfileSection";
            pProfileSection.ShadowDecoration.CustomizableEdges = customizableEdges29;
            pProfileSection.Size = new Size(1040, 448);
            pProfileSection.TabIndex = 1;
            // tlpProfileFields - 7 rows بدل 5
            tlpProfileFields.ColumnCount = 2;
            tlpProfileFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tlpProfileFields.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tlpProfileFields.Controls.Add(lblProfileInfo, 0, 0);
            tlpProfileFields.Controls.Add(lblFullName, 0, 1);
            tlpProfileFields.Controls.Add(txtFullName, 0, 2);
            tlpProfileFields.Controls.Add(lblEmail, 1, 1);
            tlpProfileFields.Controls.Add(txtEmail, 1, 2);
            tlpProfileFields.Controls.Add(lblSpeciality, 0, 3);
            tlpProfileFields.Controls.Add(txtSpeciality, 0, 4);
            tlpProfileFields.Controls.Add(lblPhone, 1, 3);
            tlpProfileFields.Controls.Add(txtPhone, 1, 4);
            tlpProfileFields.Controls.Add(lblRolePermissions, 0, 5);
            tlpProfileFields.Controls.Add(pPermissions, 0, 6);
            tlpProfileFields.Dock = DockStyle.Fill;
            tlpProfileFields.Location = new Point(0, 0);
            tlpProfileFields.Name = "tlpProfileFields";
            tlpProfileFields.RowCount = 7;
            tlpProfileFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 50F));
            tlpProfileFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            tlpProfileFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
            tlpProfileFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            tlpProfileFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
            tlpProfileFields.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            tlpProfileFields.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tlpProfileFields.Size = new Size(1040, 448);
            tlpProfileFields.TabIndex = 0;
            // lblProfileInfo
            lblProfileInfo.AutoSize = true;
            tlpProfileFields.SetColumnSpan(lblProfileInfo, 2);
            lblProfileInfo.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            lblProfileInfo.ForeColor = Color.FromArgb(17, 24, 39);
            lblProfileInfo.Location = new Point(3, 0);
            lblProfileInfo.Name = "lblProfileInfo";
            lblProfileInfo.Size = new Size(185, 21);
            lblProfileInfo.TabIndex = 0;
            lblProfileInfo.Text = "👤  Profile Information";
            // lblFullName
            lblFullName.AutoSize = true;
            lblFullName.Font = new Font("Segoe UI", 9F);
            lblFullName.ForeColor = Color.FromArgb(107, 114, 128);
            lblFullName.Location = new Point(3, 50);
            lblFullName.Name = "lblFullName";
            lblFullName.Size = new Size(61, 15);
            lblFullName.TabIndex = 1;
            lblFullName.Text = "Full Name";
            // txtFullName
            txtFullName.BorderColor = Color.FromArgb(230, 234, 242);
            txtFullName.BorderRadius = 10;
            txtFullName.CustomizableEdges = customizableEdges18;
            txtFullName.DefaultText = "";
            txtFullName.Dock = DockStyle.Fill;
            txtFullName.FillColor = Color.FromArgb(245, 247, 251);
            txtFullName.Font = new Font("Segoe UI", 10F);
            txtFullName.Location = new Point(3, 83);
            txtFullName.Margin = new Padding(3, 3, 12, 3);
            txtFullName.Name = "txtFullName";
            txtFullName.PlaceholderText = "Full Name";
            txtFullName.SelectedText = "";
            txtFullName.ShadowDecoration.CustomizableEdges = customizableEdges19;
            txtFullName.Size = new Size(505, 50);
            txtFullName.TabIndex = 0;
            // lblEmail
            lblEmail.AutoSize = true;
            lblEmail.Font = new Font("Segoe UI", 9F);
            lblEmail.ForeColor = Color.FromArgb(107, 114, 128);
            lblEmail.Location = new Point(523, 50);
            lblEmail.Name = "lblEmail";
            lblEmail.Size = new Size(81, 15);
            lblEmail.TabIndex = 2;
            lblEmail.Text = "Email Address";
            // txtEmail
            txtEmail.BorderColor = Color.FromArgb(230, 234, 242);
            txtEmail.BorderRadius = 10;
            txtEmail.CustomizableEdges = customizableEdges20;
            txtEmail.DefaultText = "";
            txtEmail.Dock = DockStyle.Fill;
            txtEmail.FillColor = Color.FromArgb(245, 247, 251);
            txtEmail.Font = new Font("Segoe UI", 10F);
            txtEmail.Location = new Point(532, 83);
            txtEmail.Margin = new Padding(12, 3, 3, 3);
            txtEmail.Name = "txtEmail";
            txtEmail.PlaceholderText = "Email Address";
            txtEmail.SelectedText = "";
            txtEmail.ShadowDecoration.CustomizableEdges = customizableEdges21;
            txtEmail.Size = new Size(505, 50);
            txtEmail.TabIndex = 1;
            // lblSpeciality
            lblSpeciality.AutoSize = true;
            lblSpeciality.Font = new Font("Segoe UI", 9F);
            lblSpeciality.ForeColor = Color.FromArgb(107, 114, 128);
            lblSpeciality.Location = new Point(3, 142);
            lblSpeciality.Name = "lblSpeciality";
            lblSpeciality.Size = new Size(61, 15);
            lblSpeciality.TabIndex = 4;
            lblSpeciality.Text = "Speciality";
            // txtSpeciality
            txtSpeciality.BorderColor = Color.FromArgb(230, 234, 242);
            txtSpeciality.BorderRadius = 10;
            txtSpeciality.CustomizableEdges = customizableEdges32;
            txtSpeciality.DefaultText = "";
            txtSpeciality.Dock = DockStyle.Fill;
            txtSpeciality.FillColor = Color.FromArgb(245, 247, 251);
            txtSpeciality.Font = new Font("Segoe UI", 10F);
            txtSpeciality.Location = new Point(3, 175);
            txtSpeciality.Margin = new Padding(3, 3, 12, 3);
            txtSpeciality.Name = "txtSpeciality";
            txtSpeciality.PlaceholderText = "Speciality";
            txtSpeciality.SelectedText = "";
            txtSpeciality.ShadowDecoration.CustomizableEdges = customizableEdges33;
            txtSpeciality.Size = new Size(505, 50);
            txtSpeciality.TabIndex = 2;
            // lblPhone
            lblPhone.AutoSize = true;
            lblPhone.Font = new Font("Segoe UI", 9F);
            lblPhone.ForeColor = Color.FromArgb(107, 114, 128);
            lblPhone.Location = new Point(523, 142);
            lblPhone.Name = "lblPhone";
            lblPhone.Size = new Size(40, 15);
            lblPhone.TabIndex = 5;
            lblPhone.Text = "Phone";
            // txtPhone
            txtPhone.BorderColor = Color.FromArgb(230, 234, 242);
            txtPhone.BorderRadius = 10;
            txtPhone.CustomizableEdges = customizableEdges34;
            txtPhone.DefaultText = "";
            txtPhone.Dock = DockStyle.Fill;
            txtPhone.FillColor = Color.FromArgb(245, 247, 251);
            txtPhone.Font = new Font("Segoe UI", 10F);
            txtPhone.Location = new Point(532, 175);
            txtPhone.Margin = new Padding(12, 3, 3, 3);
            txtPhone.Name = "txtPhone";
            txtPhone.PlaceholderText = "Phone Number";
            txtPhone.SelectedText = "";
            txtPhone.ShadowDecoration.CustomizableEdges = customizableEdges35;
            txtPhone.Size = new Size(505, 50);
            txtPhone.TabIndex = 3;
            // lblRolePermissions
            lblRolePermissions.AutoSize = true;
            tlpProfileFields.SetColumnSpan(lblRolePermissions, 2);
            lblRolePermissions.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblRolePermissions.ForeColor = Color.FromArgb(17, 24, 39);
            lblRolePermissions.Location = new Point(3, 228);
            lblRolePermissions.Name = "lblRolePermissions";
            lblRolePermissions.Size = new Size(122, 19);
            lblRolePermissions.TabIndex = 3;
            lblRolePermissions.Text = "Role Permissions";
            // pPermissions
            tlpProfileFields.SetColumnSpan(pPermissions, 2);
            pPermissions.Controls.Add(cardPermPatients);
            pPermissions.Controls.Add(cardPermAppointments);
            pPermissions.Controls.Add(cardPermReports);
            pPermissions.Dock = DockStyle.Fill;
            pPermissions.Location = new Point(3, 267);
            pPermissions.Name = "pPermissions";
            pPermissions.Size = new Size(1034, 180);
            pPermissions.TabIndex = 0;
            // cardPermPatients
            cardPermPatients.BorderColor = Color.FromArgb(230, 234, 242);
            cardPermPatients.BorderRadius = 10;
            cardPermPatients.BorderThickness = 1;
            cardPermPatients.Controls.Add(lblPermPatientsTitle);
            cardPermPatients.Controls.Add(lblPermPatientsValue);
            cardPermPatients.CustomizableEdges = customizableEdges22;
            cardPermPatients.FillColor = Color.FromArgb(245, 247, 251);
            cardPermPatients.Location = new Point(0, 0);
            cardPermPatients.Name = "cardPermPatients";
            cardPermPatients.Padding = new Padding(12);
            cardPermPatients.ShadowDecoration.CustomizableEdges = customizableEdges23;
            cardPermPatients.Size = new Size(220, 60);
            cardPermPatients.TabIndex = 0;
            // lblPermPatientsTitle
            lblPermPatientsTitle.AutoSize = true;
            lblPermPatientsTitle.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblPermPatientsTitle.ForeColor = Color.FromArgb(17, 24, 39);
            lblPermPatientsTitle.Location = new Point(12, 10);
            lblPermPatientsTitle.Name = "lblPermPatientsTitle";
            lblPermPatientsTitle.Size = new Size(69, 15);
            lblPermPatientsTitle.TabIndex = 0;
            lblPermPatientsTitle.Text = "👤  Patients";
            // lblPermPatientsValue
            lblPermPatientsValue.AutoSize = true;
            lblPermPatientsValue.Font = new Font("Segoe UI", 9F);
            lblPermPatientsValue.ForeColor = Color.FromArgb(107, 114, 128);
            lblPermPatientsValue.Location = new Point(12, 30);
            lblPermPatientsValue.Name = "lblPermPatientsValue";
            lblPermPatientsValue.Size = new Size(58, 15);
            lblPermPatientsValue.TabIndex = 1;
            lblPermPatientsValue.Text = "View & Edit";
            // cardPermAppointments
            cardPermAppointments.BorderColor = Color.FromArgb(230, 234, 242);
            cardPermAppointments.BorderRadius = 10;
            cardPermAppointments.BorderThickness = 1;
            cardPermAppointments.Controls.Add(lblPermAppointmentsTitle);
            cardPermAppointments.Controls.Add(lblPermAppointmentsValue);
            cardPermAppointments.CustomizableEdges = customizableEdges24;
            cardPermAppointments.FillColor = Color.FromArgb(245, 247, 251);
            cardPermAppointments.Location = new Point(230, 0);
            cardPermAppointments.Name = "cardPermAppointments";
            cardPermAppointments.Padding = new Padding(12);
            cardPermAppointments.ShadowDecoration.CustomizableEdges = customizableEdges25;
            cardPermAppointments.Size = new Size(220, 60);
            cardPermAppointments.TabIndex = 1;
            // lblPermAppointmentsTitle
            lblPermAppointmentsTitle.AutoSize = true;
            lblPermAppointmentsTitle.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblPermAppointmentsTitle.ForeColor = Color.FromArgb(17, 24, 39);
            lblPermAppointmentsTitle.Location = new Point(12, 10);
            lblPermAppointmentsTitle.Name = "lblPermAppointmentsTitle";
            lblPermAppointmentsTitle.Size = new Size(105, 15);
            lblPermAppointmentsTitle.TabIndex = 0;
            lblPermAppointmentsTitle.Text = "📅  Appointments";
            // lblPermAppointmentsValue
            lblPermAppointmentsValue.AutoSize = true;
            lblPermAppointmentsValue.Font = new Font("Segoe UI", 9F);
            lblPermAppointmentsValue.ForeColor = Color.FromArgb(107, 114, 128);
            lblPermAppointmentsValue.Location = new Point(12, 30);
            lblPermAppointmentsValue.Name = "lblPermAppointmentsValue";
            lblPermAppointmentsValue.Size = new Size(58, 15);
            lblPermAppointmentsValue.TabIndex = 1;
            lblPermAppointmentsValue.Text = "View only";
            // cardPermReports
            cardPermReports.BorderColor = Color.FromArgb(230, 234, 242);
            cardPermReports.BorderRadius = 10;
            cardPermReports.BorderThickness = 1;
            cardPermReports.Controls.Add(lblPermReportsTitle);
            cardPermReports.Controls.Add(lblPermReportsValue);
            cardPermReports.CustomizableEdges = customizableEdges26;
            cardPermReports.FillColor = Color.FromArgb(245, 247, 251);
            cardPermReports.Location = new Point(460, 0);
            cardPermReports.Name = "cardPermReports";
            cardPermReports.Padding = new Padding(12);
            cardPermReports.ShadowDecoration.CustomizableEdges = customizableEdges27;
            cardPermReports.Size = new Size(220, 60);
            cardPermReports.TabIndex = 2;
            // lblPermReportsTitle
            lblPermReportsTitle.AutoSize = true;
            lblPermReportsTitle.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblPermReportsTitle.ForeColor = Color.FromArgb(17, 24, 39);
            lblPermReportsTitle.Location = new Point(12, 10);
            lblPermReportsTitle.Name = "lblPermReportsTitle";
            lblPermReportsTitle.Size = new Size(70, 15);
            lblPermReportsTitle.TabIndex = 0;
            lblPermReportsTitle.Text = "📊  Reports";
            // lblPermReportsValue
            lblPermReportsValue.AutoSize = true;
            lblPermReportsValue.Font = new Font("Segoe UI", 9F);
            lblPermReportsValue.ForeColor = Color.FromArgb(107, 114, 128);
            lblPermReportsValue.Location = new Point(12, 30);
            lblPermReportsValue.Name = "lblPermReportsValue";
            lblPermReportsValue.Size = new Size(47, 15);
            lblPermReportsValue.TabIndex = 1;
            lblPermReportsValue.Text = "Limited";
            // lblProfileSub
            lblProfileSub.Location = new Point(0, 0);
            lblProfileSub.Name = "lblProfileSub";
            lblProfileSub.Size = new Size(100, 23);
            lblProfileSub.TabIndex = 0;
            // SettingsView
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(245, 247, 251);
            Controls.Add(tlpRoot);
            Name = "SettingsView";
            Padding = new Padding(24);
            Size = new Size(1148, 808);
            tlpRoot.ResumeLayout(false);
            cardHeader.ResumeLayout(false);
            tlpHeader.ResumeLayout(false);
            pHeaderText.ResumeLayout(false);
            pHeaderText.PerformLayout();
            cardTabs.ResumeLayout(false);
            tlpTabs.ResumeLayout(false);
            cardProfile.ResumeLayout(false);
            tlpProfile.ResumeLayout(false);
            pAvatarInfo.ResumeLayout(false);
            pUserInfo.ResumeLayout(false);
            pUserInfo.PerformLayout();
            pProfileSection.ResumeLayout(false);
            tlpProfileFields.ResumeLayout(false);
            tlpProfileFields.PerformLayout();
            pPermissions.ResumeLayout(false);
            cardPermPatients.ResumeLayout(false);
            cardPermPatients.PerformLayout();
            cardPermAppointments.ResumeLayout(false);
            cardPermAppointments.PerformLayout();
            cardPermReports.ResumeLayout(false);
            cardPermReports.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private TableLayoutPanel tlpRoot;
        private Guna.UI2.WinForms.Guna2Panel cardHeader;
        private TableLayoutPanel tlpHeader;
        private Panel pHeaderText;
        private Label lblTitle;
        private Label lblSubtitle;
        private Guna.UI2.WinForms.Guna2Button btnSave;
        private Guna.UI2.WinForms.Guna2Panel cardTabs;
        private TableLayoutPanel tlpTabs;
        private Guna.UI2.WinForms.Guna2Button btnTabProfile;
        private Guna.UI2.WinForms.Guna2Button btnTabQueue;
        private Guna.UI2.WinForms.Guna2Button btnTabSystem;
        private Guna.UI2.WinForms.Guna2Panel cardProfile;
        private TableLayoutPanel tlpProfile;
        private Panel pAvatarInfo;
        private Guna.UI2.WinForms.Guna2CircleButton btnAvatar;
        private Panel pUserInfo;
        private Label lblUserName;
        private Label lblUserEmail;
        private Guna.UI2.WinForms.Guna2Button lblUserRole;
        private Guna.UI2.WinForms.Guna2Panel pProfileSection;
        private TableLayoutPanel tlpProfileFields;
        private Label lblProfileInfo;
        private Label lblProfileSub;
        private Label lblFullName;
        private Guna.UI2.WinForms.Guna2TextBox txtFullName;
        private Label lblEmail;
        private Guna.UI2.WinForms.Guna2TextBox txtEmail;
        private Label lblSpeciality;
        private Guna.UI2.WinForms.Guna2TextBox txtSpeciality;
        private Label lblPhone;
        private Guna.UI2.WinForms.Guna2TextBox txtPhone;
        private Label lblRolePermissions;
        private Panel pPermissions;
        private Guna.UI2.WinForms.Guna2Panel cardPermPatients;
        private Label lblPermPatientsTitle;
        private Label lblPermPatientsValue;
        private Guna.UI2.WinForms.Guna2Panel cardPermAppointments;
        private Label lblPermAppointmentsTitle;
        private Label lblPermAppointmentsValue;
        private Guna.UI2.WinForms.Guna2Panel cardPermReports;
        private Label lblPermReportsTitle;
        private Label lblPermReportsValue;
    }
}